### ISSUE TITLE
Include title bar colour in theme

### ISSUE THREAD

**Issue by tempertemper** [TheBaronHimself/Spaceblack#13]
Really love your theme (Spacegray isn't dark enough for me). Is it possible to update it to make the title bar on the window take theme's colour, rather than the default light grey. Here's a screenshot of the window with the matching dark grey in Spacegray:

![spacegray](https://user-images.githubusercontent.com/2418781/50781974-9eceda80-129e-11e9-89fd-4201a582556c.png)

And here's the same window in Spaceblack:

![spaceblack](https://user-images.githubusercontent.com/2418781/50781975-9eceda80-129e-11e9-86e0-ccda6aa56e27.png)

Thanks for taking a look!

**Comment by TheBaronHimself** [comment]
Hey tempertemper,

Thanks for your kind words. I'm glad you like the theme. However, I'm not actively developing it anymore and would actually like to transfer the repo to someone who'd be willing to maintain it in the future. @saadq, would you be up for that?

Best wishes,
Simon-Claudius

**Comment by saadq** [comment]
Hmm, unfortunately I don't think I'd be be the best person to maintain the package as I don't use Sublime Text anymore, and I already have too many open issues for other stuff. 

However, this turned out to be an easy fix so I opened a PR for it. I think if you push a new version it should be good to go. Also, I think the theme is pretty "complete" so I doubt there will be too many more issues aside from stuff like this when new Sublime features come, so in case you can't find another maintainer feel free to ping me when an issue comes up and I can take a look.

![screen shot 2019-01-15 at 4 02 09 am](https://user-images.githubusercontent.com/5678694/51169611-5d2fc800-187a-11e9-8563-70c9b4619a4a.png)

**Comment by TheBaronHimself** [comment]
Excellent. Thanks, Saad! I'm in the same boat as you, actually. I don't use Sublime Text myself anymore. 

@tempertemper, is Saad's contribution to your satisfaction?

**Comment by tempertemper** [comment]
Gentlemen, thank you both! It looks like exactly what I was after but I can only tell from the Saad's screenshot as I can't get it to take effect on my machine.

It should just happen by default, shouldn't it? [The PR](https://github.com/TheBaronHimself/Spaceblack/pull/14/files) suggests it's not a disable-able option. Package control is telling me all my packages are up to date, and removing then re-installing the theme isn't helping either.

**Comment by tempertemper** [comment]
Could it be because the version number hasn't updated with this change? Maybe that's what package control uses to pull new versions down (I have no idea…)? @saadq @TheBaronHimself

**Comment by saadq** [comment]
Yeah, Package Control uses git tags to manage the package versions. I am not sure if Simon-Claudius has pushed a new version tag after accepting the PR, will need to wait for his response.

**Comment by TheBaronHimself** [comment]
Done. Should update on Package Control soon.

**Comment by tempertemper** [comment]
Updated and works a treat. Thank you both very much!
