### ISSUE TITLE
Keep getting errors after restart sublime

### ISSUE THREAD

**Issue by Samjin** [TheBaronHimself/Spaceblack#8]
![error](https://cloud.githubusercontent.com/assets/6115094/9044927/ca17c32e-39d4-11e5-97de-ff56c8d29903.jpg)
Any clue how to fix this?

**Comment by saadq** [comment]
Hi Sam,

Did you install the theme through Package Control or did you manually download the ZIP?

**Comment by saadq** [comment]
Hi Sam,

I recently updated the folder name because there is more than one color scheme.

Instead of 
`"color_scheme": "Packages/Theme - Spaceblack/Color Scheme/Spaceblack-alt.tmTheme",` 

it should be
`"color_scheme": "Packages/Theme - Spaceblack/Color Schemes/Spaceblack-alt.tmTheme",`

---

Thanks for raising the issue, I've updated the README.md as well. Please let me know if you have any further issues.
